docs: Disable rst2pdf due to bug with Python 3
$ make html
sphinx-build -b html -d build/doctrees   . build/html
Running Sphinx v3.0.3

Exception occurred:
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/mnt/d/libLAS.wsl/.pyenv/lib/python3.5/site-packages/rst2pdf/pdfbuilder.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax